# Generated by Django 4.2.4 on 2023-11-05 16:19

import Tracker.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_alter_locationhistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackernode',
            name='group',
        ),
        migrations.AddField(
            model_name='trackernode',
            name='node_id',
            field=models.CharField(default=Tracker.models.generate_random_string, max_length=10),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('number', models.CharField(max_length=1024)),
                ('latitude', models.DecimalField(decimal_places=24, max_digits=50)),
                ('longitude', models.DecimalField(decimal_places=24, max_digits=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracker.organization')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('phone', models.CharField(max_length=1024)),
                ('email', models.CharField(max_length=1024)),
                ('license_number', models.CharField(max_length=1024)),
                ('license_expiry', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=1024)),
                ('city', models.CharField(max_length=1024)),
                ('state', models.CharField(max_length=1024)),
                ('country', models.CharField(max_length=1024)),
                ('pincode', models.CharField(max_length=1024)),
                ('latitude', models.DecimalField(decimal_places=24, max_digits=50)),
                ('longitude', models.DecimalField(decimal_places=24, max_digits=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracker.organization')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.AddField(
            model_name='trackernode',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tracker.vehicle'),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tracker.driver'),
        ),
    ]
