# Generated by Django 4.2.4 on 2023-11-05 16:19

import Tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0004_remove_trackernode_group_trackernode_node_id_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackernode',
            name='node_id',
            field=models.CharField(default=Tracker.models.generate_random_string, max_length=10, unique=True),
        ),
    ]
