# Generated by Django 4.2.4 on 2023-11-05 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0006_remove_vehicle_latitude_remove_vehicle_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='longitude',
        ),
    ]
