# Generated by Django 4.2.4 on 2023-11-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0008_trackernode_group_alter_trackernode_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
